# Generated by Django 5.2.1 on 2025-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_message_delete_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
