# Generated by Django 5.2.1 on 2025-11-07 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conversation_updated_at_message_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('context', models.TextField(blank=True, null=True)),
                ('ground_truth', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('context', models.TextField(blank=True, null=True)),
                ('llm_answer', models.TextField()),
                ('ground_truth', models.TextField(blank=True, null=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('bert_score', models.FloatField(blank=True, null=True)),
                ('llm_rubric_score', models.FloatField(blank=True, null=True)),
                ('combined_score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('evaluation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluation_details', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.CharField(default='none', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
