# Generated by Django 5.2.1 on 2025-11-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_groundtruth_evaluationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='ragas_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='ragas_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
