# Generated by Django 5.2.1 on 2025-12-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evaluationresult_ragas_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('user_query', models.TextField()),
                ('response_text', models.TextField()),
                ('score_faithfulness', models.FloatField(blank=True, null=True)),
                ('score_answer_relevancy', models.FloatField(blank=True, null=True)),
                ('score_context_precision', models.FloatField(blank=True, null=True)),
                ('score_context_recall', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EvaluationResult',
        ),
    ]
