# Generated by Django 5.2.1 on 2025-12-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_evaluationrecord_delete_evaluationresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationrecord',
            old_name='response_text',
            new_name='ai_response',
        ),
        migrations.RenameField(
            model_name='evaluationrecord',
            old_name='score_answer_relevancy',
            new_name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='evaluationrecord',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='evaluationrecord',
            name='score_context_precision',
        ),
        migrations.RemoveField(
            model_name='evaluationrecord',
            name='score_context_recall',
        ),
        migrations.RemoveField(
            model_name='evaluationrecord',
            name='score_faithfulness',
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='hybrid_mode',
            field=models.CharField(default='hybrid', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='rag_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluationrecord',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
