# Generated by Django 5.2.1 on 2025-12-04 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_response_text_evaluationrecord_ai_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrecord',
            name='accuracy_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='completeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='educational_value_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='flagged_incorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='human_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='human_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='matched_ground_truth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='core.groundtruth'),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='similarity_to_truth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='evaluationrecord',
            index=models.Index(fields=['session_id'], name='core_evalua_session_bf1e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrecord',
            index=models.Index(fields=['flagged_incorrect'], name='core_evalua_flagged_d36d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrecord',
            index=models.Index(fields=['created_at'], name='core_evalua_created_fd97d4_idx'),
        ),
    ]
